version: '3'

services:
  dotnet:
    container_name: dotnet-barros
    build: dotnet/dotnet
    ports:
      - 80:80
    mem_limit: "50mb"
    cpus: 0.00001

  prometheus:
    image: prom/prometheus:v2.30.3
    container_name: prometheus-barros
    ports:
      - 9090:9090
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    command: --web.enable-lifecycle  --config.file=/etc/prometheus/prometheus.yml

  grafana:
      image: grafana/grafana:7.5.7
      container_name: grafana-barros
      ports:
        - 3000:3000
      restart: unless-stopped
      volumes:
        - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
        - grafana-data:/var/lib/grafana
    
volumes:
  prometheus-data:
  grafana-data: