version: '3'

services:
  dotnet:
    container_name: dotnet-barros
    build: dotnet/dotnet
    ports:
      - 3000:80
    networks:
      - barros-network

  prometheus:
    image: prom/prometheus:v2.30.3
    container_name: prometheus-barros
    ports:
      - 3001:9090
    networks:
      - barros-network
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    command: --web.enable-lifecycle  --config.file=/etc/prometheus/prometheus.yml 

  alertmanager:
    image: prom/alertmanager
    container_name: alertmanager-barros
    ports:
      - 3002:9093
    networks:
      - barros-network
    volumes:
      - ./alertmanager:/etc/alertmanager
      - alertmanager-data:/alertmanager
    command: --config.file=/etc/alertmanager/alertmanager.yml 

  grafana:
      image: grafana/grafana
      container_name: grafana-barros
      ports:
        - 3003:3000
      networks:
      - barros-network
      restart: unless-stopped
      volumes:
        - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
        - grafana-data:/var/lib/grafana
    
volumes:
  prometheus-data:
  grafana-data:
  alertmanager-data:

networks:
  barros-network:
    driver: bridge