
global:
  scrape_interval: 5s
  scrape_timeout: 5s

rule_files:
  - alerts.yml

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093

scrape_configs:
  - job_name: services
    metrics_path: /metrics
    static_configs:
      - targets:
          - 'dotnet'
