{
 "title": "Demo",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Server Up",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "targets": [
    { "expr": "up", "legendFormat": "Server Up?" }
   ]
  },
  {
   "title": "Bad Request Percentage - Payment",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(http_requests_received_total{instance=\"dotnet:80\", code=\"400\", controller=\"Payment\"}) * 100) / (sum(http_requests_received_total{instance=\"dotnet:80\", controller=\"Payment\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bad Request Percentage - User",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(http_requests_received_total{instance=\"dotnet:80\", code=\"400\", controller=\"User\"}) * 100) / (sum(http_requests_received_total{instance=\"dotnet:80\", controller=\"User\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dotnet_total_memory_bytes{instance=\"dotnet:80\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bad Request Percentage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(http_requests_received_total{instance=\"dotnet:80\", code=\"400\"}) * 100) / (sum(http_requests_received_total{instance=\"dotnet:80\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "System Runtime CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_runtime_cpu_usage{instance=\"dotnet:80\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "% Time in GC since last GC",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_runtime_time_in_gc{instance=\"dotnet:80\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Bad Requests",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_requests_received_total{instance=\"dotnet:80\", code=\"400\"}",
     "legendFormat": "{{controller}} @ {{code}}"
    }
   ]
  },
  {
   "title": "Total Success Requests",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_requests_received_total{instance=\"dotnet:80\", code=\"200\"}",
     "legendFormat": "{{controller}} @ {{code}}"
    }
   ]
  },
  {
   "title": "Requests In Progress",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "http_requests_in_progress{instance=\"dotnet:80\"}",
     "legendFormat": "{{controller}} - {{method}}"
    }
   ]
  },
  {
   "title": "Average Request Response Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_sum[5m])) / sum(rate(http_request_duration_seconds_count[5m]))",
     "legendFormat": "Seconds"
    }
   ]
  }
 ]
}